// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13EVELs6DazPSkdEVCtNcSbKU2b6G2CA',
    appId: '1:459053770398:web:535c7c15f4a163d281fd8f',
    messagingSenderId: '459053770398',
    projectId: 'sever-monitoring-system',
    authDomain: 'sever-monitoring-system.firebaseapp.com',
    databaseURL: 'https://sever-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sever-monitoring-system.appspot.com',
    measurementId: 'G-Z4D0XMYN4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfXgnvxRkAu8DyBoDNlFGBaFBhiQAY8M',
    appId: '1:459053770398:android:04a11e2b9a96f1e181fd8f',
    messagingSenderId: '459053770398',
    projectId: 'sever-monitoring-system',
    databaseURL: 'https://sever-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sever-monitoring-system.appspot.com',
  );
}
